### ISSUE TITLE
[Bug] 默认主题色还是总是初始化为暗黑主题

### ISSUE THREAD

**Issue by imingz** [ChangeSuger/fuxuan-archive#5]
### 问题描述

我清楚本地 localstorage 后发现默认主题色依然是 暗黑主题。
![image](https://github.com/ChangeSuger/fuxuan-archive/assets/57054141/6241afa1-15fe-43fa-a971-f910dd7a2565)
我通过观察 1.5 的更新日志，发现好像做过一次修改，但是好像没有生效。

后续有计划升级为跟随浏览器模式吗？

### 复现流程

1. 清除 local storage
2. 刷新页面

**Comment by ChangeSuger** [comment]
目前默认是使用暗黑主题，所以清除本地 localstorage 后显示的是暗黑主题这点是没问题的

https://github.com/ChangeSuger/fuxuan-archive/blob/646167aa8bb1e57bc7fa51ce25b0fd67989d7885/src/stores/settings.ts#L16

不过默认使用暗黑主题有我个人偏好的原因，对其他使用者来说确实不友好，后续这边会改进并支持默认跟随浏览器模式~

- [ ] 默认主题色初始化为浅色模式
- [ ] 支持主题色默认跟随浏览器模式

**Comment by imingz** [comment]
明白了
